### PR TITLE
change xml character escaping to rely on apache commons StringEscapeUtils

### PR DESCRIPTION
**Pull request by isanvicente**
I've had some problems with reading and writing NAF files containing malformed XML characters (introduced by the pos-tagged). This version solves those issues by means of org.apache.commons.lang3.StringEscapeUtils. I've made changes to the ReadWriteManager class and updated pom file with the new dependency. 

You may run some tests before merging though.

Cheers!

Iñaki.

### CODE REVIEW

**Comment by ragerri** [comment]
This commit has introduced undesired behaviour in the tools using the library. For example, if the token contains an apostrophe, the output is wrongly escaped when read to lemmatize, among other tasks, and we are trying to lemmatize `&apos;` which is not really what we want to do :)

As it can be seen in the committed changes, this happens for other tasks as well. 

https://github.com/ixa-ehu/kaflib/pull/6/commits/938abb1bd9a1919f2052acbe9c61e3bcb42d471f#diff-a719d58c68c720fe9ebffbfe06b9bb22R2239

1.1.15 version of the library works fine.

**Comment by isanvicente** [comment]
Can you show some example? I'm not sure if I follow. 

The commit only escapes tokens in comments (which are not used for any task as far as I know...), except for the [line 2239](https://github.com/ixa-ehu/kaflib/commit/938abb1bd9a1919f2052acbe9c61e3bcb42d471f#diff-a719d58c68c720fe9ebffbfe06b9bb22R2239), where the content of the lemma is also escaped. However lemmatization has already been done by then, so lemma should theoretically be free from the apostrophes. 

I've tried pos tagging a pair of examples en English and French and they seem to be working fine:

en - It's strange that he hasn't arrived yet
fr - La Cour de sûreté de l'État est, en France, une ancienne juridiction d'exception qui avait pour but de juger les personnes accusées de porter atteinte à la sûreté de l'État.

[en.naf.txt](https://github.com/ixa-ehu/kaflib/files/1816273/en.naf.txt)
[fr.naf.txt](https://github.com/ixa-ehu/kaflib/files/1816274/fr.naf.txt)

Am I missing something?

**Comment by ixa-ehu** [comment]
Changing this line 

https://github.com/ixa-ehu/kaflib/blob/naf/src/main/java/ixa/kaflib/ReadWriteManager.java#L2239

makes it work properly again.

Cheers

**Comment by ragerri** [comment]
It would be nice if you could make this change and especially, if you could deploy it to maven central.

**Comment by zbeloki** [comment]
The bug has been fixed and version 1.1.19 is now available in Maven Central.

**Comment by ragerri** [comment]
Excellent!

**Pull request merged**
